### PR TITLE
Fix: Remove useless elseif

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] removes useless `elseif`

💁‍♂️ No need for an `elseif` if we `return` already!

### CODE REVIEW

**Comment by staabm** [comment]
awesome, thx.

**Comment by localheinz** [comment]
Thank you, @staabm!

**Comment by staabm** [comment]
@localheinz  out of curiosity. do you create this pull requests using a robot or similar?

they seem to be too consistent to be created manually ;)

**Comment by localheinz** [comment]
Ha, thanks a lot, @staabm, I appreciate it and understand it as a compliment!

🤖

**Comment by staabm** [comment]
really great job, well done! ;)

**Pull request merged**
