### PR TITLE
Create FUNDING.yml

### PR DESCRIPTION
**Pull request by staabm**
See https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository

### CODE REVIEW

**Comment by staabm** [comment]
this PR should only be merged, after either staabm or jmglsn is accepted as a member of the github sponsors beta program.

otherwise we just get "Sponsor" button without functionality.

**Comment by jmglsn** [comment]
@staabm did you apply for the sponsors program?

**Comment by staabm** [comment]
I did, wasnt acceptrd yet

**Comment by staabm** [comment]
Was accepted today. Lets see if this works

**Pull request merged**
