### PR TITLE
Ensure if a content length is specified, we wait for the full body.

### LINKED ISSUE #53: NULL octets in body aren't handled properly
STOMP specification states:

> The SEND, MESSAGE and ERROR frames SHOULD include a content-length header if a frame body is present. If a frame's body contains NULL octets, the frame MUST include a content-length header. The header is a byte count for the length of the message body. If a content-length header is included, this number of bytes MUST be read, regardless of whether or not there are null characters in the body. The frame still needs to be terminated with a null byte.
> - https://stomp.github.io/stomp-specification-1.1.html#Header_content-length

So it is valid for body to contain NULL octets and the `content-length` header should be respected _over_ NULL octets as an end character.

However, `\Stomp\Network\Connection::readFrame` and `\Stomp\Transport\Parser::detectFrameEnd` both simply look for a NULL octet (or the end of the stream). This results in messages where the body contains a NULL octet getting truncated (in my case the body is gzip compressed).

### PR DESCRIPTION
**Pull request by andrewbelcher**
Fixes #53.

### CODE REVIEW

**Comment by staabm** [comment]
please make sure to include a unit test, which fails without your changes

**Comment by jmglsn** [comment]
@staabm I'll check if we can create an easy backport for version 3.

**Comment by staabm** [comment]
Awesome, thx guys.

**Comment by jmglsn** [comment]
Will be included on our next 4.x release. 
Version 3.x has no null byte handling at all...

**Pull request merged**
