### PR TITLE
Stomp Client Version 3.0.0

### PR DESCRIPTION
**Pull request by jmglsn**
This could be the first release from our new stomp-php repository.

I tried to collect most changes seen on the original repository network graph. These changes have been applied against a already modified code base, which means that there is no direct backwards compatibility.

- This versions aims to be pretty close to the previous https://github.com/dejanb/stomp-php/releases/tag/2.1.1
- It should be the last php-5.3 compatible version.
- It uses a new namespace (Stomp)

### CODE REVIEW

**Comment by chuhlomin** [comment]
Since we are not going to support backwards compatibility, how about move login&password from Stomp::connect() to Stomp::__construct()? 
Most unlikely that someone using different logins in one script.
And in real project, using service locator like Pimple, it's better to put in container "ready-to-use" Stomp client with given broker, login and pass.

As for pull-request, all looks good for me.

**Comment by jmglsn** [comment]
You're absolutely right. I'll change this. 
Do you agree with the new namespace? I was not completely sure about it, only about the fact of a needed change.

**Comment by chuhlomin** [comment]
Yeah, namespace Stomp is ok for me.

**Comment by jmglsn** [comment]
I would like to include #5 here too.

**Comment by chuhlomin** [comment]
We can't do everything at once :-)
Maybe we just merge it, continue developing and release 3.0.0 later?

**Comment by jmglsn** [comment]
Yes, let's keep that as an extra task :)

**Pull request merged**
