### PR TITLE
PHP 7.4 + 8, PHPUnit 9.5

### PR DESCRIPTION
**Pull request by andrewmy**
- Add PHP 7.4 and 8 to the build matrix;
- 7.4 introduced some deprecations for PHPUnit, only fixed in 8.2.3 + we need PHP 8 support => update PHPUnit to 9.5;
- Drop PHP < 7.3 (unsupported by newer PHPUnit and are EOL anyway);
- Adapt tests to the new PHPUnit.

Replaces #156

### CODE REVIEW

**Comment by andrewmy** [comment]
@staabm @jmglsn take a look please

**Comment by andrewmy** [comment]
@staabm, @jmglsn, what do you think?

**Review by staabm — APPROVED** [review]
From my POV this looks good, thx

**Comment by jmglsn** [comment]
@andrewmy great, thank you!!

**Comment by andrewmy** [comment]
Amazing! Could you please do a release?

**Comment by jmglsn** [comment]
Here you go https://github.com/stomp-php/stomp-php/releases/tag/5.0.0 :)

**Comment by andrewmy** [comment]
Thank you!

**Pull request merged**
