### PR TITLE
Missing durable flag on ActiveMQ connection.

### PR DESCRIPTION
**Pull request by riskawarrior**
There was missing the durable flag on activemq connection.

### CODE REVIEW

**Comment by jmglsn** [comment]
Hi @riskawarrior,

where did you find the header `durable`? Thought it's `activemq.subscriptionName`.
- https://activemq.apache.org/apollo/documentation/stomp-manual.html
- http://activemq.apache.org/stomp.html

**Comment by riskawarrior** [comment]
Hi @jmglsn,

Here:
* https://activemq.apache.org/apollo/documentation/stomp-manual.html#Topic_Durable_Subscriptions

Apollo no longer uses `activemq.*` flags, instead it uses the `persistent` flag.

It might be worth to separate ActiveMQ and Apollo protocols.

**Comment by jmglsn** [comment]
I missed that. Yes, it would be the best to add a new protocol for Apollo, to keep different implementations clear. I'll do that in 2 days, I'm a little bit busy currently, sorry for that.

**Comment by riskawarrior** [comment]
Nevermind that. I added the new interface to this pull request.

**Pull request closed without merging**
