### PR TITLE
prepare release 4.1

### PR DESCRIPTION
**Pull request by jmglsn**
- updated AMQ ci test version from 5.13.0 to 5.13.3
- updated RMQ ci test version from 3.5.6 to 3.6.2
- updated durable tests for RMQ (pass 'auto-delete' header and replaced 'persistent' with 'durable' header)
- updated erlang from R14B04 to latest version (travis)
- increase read timeout for amq abort test (will fix https://github.com/stomp-php/stomp-php/issues/49#issuecomment-222366867)

### CODE REVIEW

**Comment by staabm** [comment]
Do we really need the composer selfupdate ?

**Comment by jmglsn** [comment]
This is everything I would like to include for 4.1.

**Comment by staabm** [comment]
Looks great, thx

**Comment by jmglsn** [comment]
The `composer self update` is done by the travis php image.

**Comment by staabm** [comment]
Ohh you are right. Seems they added it recently. Nothing todo here. Move along ;).

**Pull request merged**
